export const _ALL_EXPORT_COLUMNS: [string, string][] = [
	['derived_status', 'Status'],
	['received_date', 'Received Date'],
	['job_date', 'Job Date'],
	['job_no', 'Job No'],
	['job_card_no', 'Job Card No'],
	['model_no', 'Model No'],
	['blank_no', 'Blank No'],
	['serial_no', 'Serial No'],
	['customer', 'Customer'],
	['remarks', 'Remarks'],
	['curing', 'Curing'],
	['post_curing', 'Post Curing'],
	['wiring', 'Wiring'],
	['tc0', 'TC0'],
	['cycling', 'Cycling'],
	['cabling', 'Cabling'],
	['trimming', 'Trimming'],
	['black_putty', 'Black Putty'],
	['bellow_welding', 'Bellow Welding'],
	['pocket_welding', 'Pocket Welding'],
	['sealing_side_1', 'Sealing Side 1'],
	['sealing_side_2', 'Sealing Side 2'],
	['linearity', 'Linearity'],
	['tc0_qc', 'TC0 QC'],
	['tinning', 'Tinning'],
	['ready_date', 'Ready Date'],
	['dispatch_date', 'Dispatch Date']
];
